FROM ubuntu:18.04 as base

# This image supports:
#    - GCC 5.5, 6.5, 7.5, 8.4
#    - Clang 5.0, 6.0, 7.0, 8.0, 9.0, 10.0

# Architecture: amd64 or arm64
ARG ARCH

# Basics
RUN set -x && echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections && \
    apt-get update && \
    apt-get install -y -q apt-transport-https ca-certificates && \
    apt-get install -y -q curl gnupg && \
    apt-get install -y -q make git python3 cmake

# GCC
RUN apt-get update && \
    apt-get install -y -q g++-5 g++-6 g++-7 g++-8 && \
    if [ "$ARCH" != "arm64" ]; then \
        apt-get install -y -q g++-5-multilib g++-6-multilib g++-7-multilib g++-8-multilib; \
    fi

# Clang
RUN curl -sSL "http://apt.llvm.org/llvm-snapshot.gpg.key" | apt-key add - && \
    echo "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-5.0 main" | tee -a /etc/apt/sources.list > /dev/null && \
    echo "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-6.0 main" | tee -a /etc/apt/sources.list > /dev/null && \
    echo "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-7 main" | tee -a /etc/apt/sources.list > /dev/null && \
    echo "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-8 main" | tee -a /etc/apt/sources.list > /dev/null && \
    echo "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main" | tee -a /etc/apt/sources.list > /dev/null && \
    echo "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main" | tee -a /etc/apt/sources.list > /dev/null && \
    apt-get update && \
    apt-get install -y -q clang-5.0 clang-6.0 clang-7 clang-8 clang-9 clang-10

WORKDIR /project-src

CMD ["bash"]
