FROM ubuntu:20.04 as base

# This image supports:
#    - GCC 9.4, 10.3, 11.1
#    - Clang 11.0 (arm64), 11.1 (amd64), 12.0, 13.0, 14.0

# Architecture: amd64 or arm64
ARG ARCH

# Basics
# software-properties-common is used for add-apt-repository
RUN set -x && echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections && \
    apt-get update && \
    apt-get install -y -q apt-transport-https ca-certificates && \
    apt-get install -y -q software-properties-common && \
    apt-get install -y -q curl gnupg && \
    apt-get install -y -q make git python3 cmake

# GCC
# We need ubuntu-toolchain-r/test for gcc11
RUN add-apt-repository ppa:ubuntu-toolchain-r/test && \
    apt-get update && \
    apt-get install -y -q g++-9 g++-10 g++-11 && \
    if [ "$ARCH" != "arm64" ]; then \
        apt-get install -y -q g++-9-multilib g++-10-multilib g++-11-multilib; \
    fi

# Clang
RUN curl -sSL "http://apt.llvm.org/llvm-snapshot.gpg.key" | apt-key add - && \
    echo "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-11 main" | tee -a /etc/apt/sources.list > /dev/null && \
    echo "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-12 main" | tee -a /etc/apt/sources.list > /dev/null && \
    echo "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-13 main" | tee -a /etc/apt/sources.list > /dev/null && \
    echo "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-14 main" | tee -a /etc/apt/sources.list > /dev/null && \
    apt-get update && \
    apt-get install -y -q clang-11 clang-12 clang-13 clang-14

WORKDIR /project-src

CMD ["bash"]
