FROM ubuntu:16.04 as base

# This image supports:
#    - GCC 4.9, 5.4
#    - Clang 4.0

# Architecture: amd64 or arm64
ARG ARCH

# Basics
RUN set -x && echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections && \
    apt-get update && \
    apt-get install -y -q apt-transport-https ca-certificates && \
    apt-get install -y -q curl gnupg && \
    apt-get install -y -q make git python3 cmake

# GCC
RUN apt-get update && \
    apt-get install -y -q g++-4.9 g++-5 && \
    if [ "$ARCH" != "arm64" ]; then \
        apt-get install -y -q g++-4.9-multilib g++-5-multilib; \
    fi

# Clang
RUN curl -sSL "http://apt.llvm.org/llvm-snapshot.gpg.key" | apt-key add - && \
    echo "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-4.0 main" | tee -a /etc/apt/sources.list > /dev/null && \
    apt-get update && \
    apt-get install -y -q clang-4.0

WORKDIR /project-src

CMD ["bash"]
